def get_code_langs():
    return [[164, 'MPASM', True],
            [165, 'MXML', True],
            [166, 'MySQL', True],
            [167, 'Nagios', True],
            [160, 'MIX Assembler', True],
            [161, 'Modula 2', True],
            [162, 'Modula 3', True],
            [163, 'Motorola 68000 HiSoft Dev', True],
            [173, 'NullSoft Installer', True],
            [174, 'Oberon 2', True],
            [175, 'Objeck Programming Langua', True],
            [168, 'NetRexx', True],
            [169, 'newLISP', True],
            [170, 'Nginx', True],
            [171, 'Nimrod', True],
            [84, 'DCL', True],
            [85, 'DCPU-16', True],
            [86, 'DCS', True],
            [87, 'Delphi', True],
            [81, 'Cuesheet', True],
            [82, 'D', True],
            [83, 'Dart', True],
            [92, 'E', True],
            [93, 'Easytrieve', True],
            [94, 'ECMAScript', True],
            [95, 'Eiffel', True],
            [88, 'Delphi Prism (Oxygene)', True],
            [89, 'Diff', True],
            [90, 'DIV', True],
            [91, 'DOT', True],
            [68, 'CAD Lisp', True],
            [69, 'Ceylon', True],
            [70, 'CFDG', True],
            [71, 'ChaiScript', True],
            [64, 'C++ WinAPI', True],
            [65, 'C++ with Qt extensions', True],
            [66, 'C: Loadrunner', True],
            [67, 'CAD DCL', True],
            [76, 'CMake', True],
            [77, 'COBOL', True],
            [78, 'CoffeeScript', True],
            [79, 'ColdFusion', True],
            [72, 'Chapel', True],
            [73, 'Clojure', True],
            [74, 'Clone C', True],
            [75, 'Clone C++', True],
            [116, 'GwBasic', True],
            [117, 'Haskell', True],
            [118, 'Haxe', True],
            [119, 'HicEst', True],
            [112, 'Genie', True],
            [113, 'GetText', True],
            [114, 'Go', True],
            [115, 'Groovy', True],
            [124, 'IDL', True],
            [125, 'INI file', True],
            [126, 'Inno Script', True],
            [127, 'INTERCAL', True],
            [120, 'HQ9 Plus', True],
            [122, 'HTML 5', True],
            [123, 'Icon', True],
            [100, 'F#', True],
            [101, 'Falcon', True],
            [102, 'Filemaker', True],
            [103, 'FO Language', True],
            [96, 'Email', True],
            [97, 'EPC', True],
            [98, 'Erlang', True],
            [99, 'Euphoria', True],
            [108, 'GAMBAS', True],
            [109, 'Game Maker', True],
            [110, 'GDB', True],
            [111, 'Genero', True],
            [104, 'Formula One', True],
            [105, 'Fortran', True],
            [106, 'FreeBasic', True],
            [107, 'FreeSWITCH', True],
            [20, '6502 ACME Cross Assembler', True],
            [21, '6502 Kick Assembler', True],
            [22, '6502 TASM/64TASS', True],
            [23, 'ABAP', True],
            [16, 'Python', True],
            [17, 'Ruby', True],
            [18, 'Swift', True],
            [19, '4CS', True],
            [28, 'ALGOL 68', True],
            [29, 'Apache Log', True],
            [30, 'AppleScript', True],
            [31, 'APT Sources', True],
            [24, 'ActionScript', True],
            [25, 'ActionScript 3', True],
            [26, 'Ada', True],
            [27, 'AIMMS', True],
            [4, 'C#', True],
            [5, 'C++', True],
            [6, 'CSS', True],
            [7, 'HTML', True],
            [1, 'None', True],
            [2, 'Bash', True],
            [3, 'C', True],
            [12, 'Markdown', True],
            [13, 'Objective C', True],
            [14, 'Perl', True],
            [15, 'PHP', True],
            [8, 'Java', True],
            [9, 'JavaScript', True],
            [10, 'JSON', True],
            [11, 'Lua', True],
            [52, 'Blitz Basic', True],
            [53, 'Blitz3D', True],
            [54, 'BlitzMax', True],
            [55, 'BNF', True],
            [49, 'Basic4GL', True],
            [50, 'Batch', True],
            [51, 'BibTeX', True],
            [60, 'C for Macs', True],
            [61, 'C Intermediate Language', True],
            [56, 'BOO', True],
            [57, 'BrainFuck', True],
            [59, 'C WinAPI', True],
            [36, 'autoconf', True],
            [37, 'Autohotkey', True],
            [38, 'AutoIt', True],
            [39, 'Avisynth', True],
            [32, 'ARM', True],
            [33, 'ASM (NASM)', True],
            [34, 'ASP', True],
            [35, 'Asymptote', True],
            [47, 'BASCOM AVR', True],
            [40, 'Awk', True],
            [276, 'Z80 Assembler', True],
            [277, 'ZXBasic', True],
            [272, 'XML', True],
            [273, 'Xorg Config', True],
            [274, 'XPP', True],
            [275, 'YAML', True],
            [260, 'VBScript', True],
            [261, 'Vedit', True],
            [262, 'VeriLog', True],
            [263, 'VHDL', True],
            [256, 'UPC', True],
            [257, 'Urbi', True],
            [258, 'Vala', True],
            [259, 'VB.NET', True],
            [268, 'WhiteSpace', True],
            [269, 'WHOIS', True],
            [270, 'Winbatch', True],
            [271, 'XBasic', True],
            [264, 'VIM', True],
            [265, 'Visual Pro Log', True],
            [266, 'VisualBasic', True],
            [267, 'VisualFoxPro', True],
            [212, 'Puppet', True],
            [213, 'PureBasic', True],
            [214, 'PyCon', True],
            [208, 'Progress', True],
            [209, 'Prolog', True],
            [210, 'Properties', True],
            [211, 'ProvideX', True],
            [220, 'R', True],
            [221, 'Racket', True],
            [222, 'Rails', True],
            [223, 'RBScript', True],
            [216, 'Python for S60', True],
            [217, 'q/kdb+', True],
            [218, 'QBasic', True],
            [219, 'QML', True],
            [196, 'PHP Brief', True],
            [197, 'Pic 16', True],
            [198, 'Pike', True],
            [199, 'Pixel Bender', True],
            [192, 'Per', True],
            [194, 'Perl 6', True],
            [204, 'POV-Ray', True],
            [205, 'Power Shell', True],
            [206, 'PowerBuilder', True],
            [207, 'ProFTPd', True],
            [200, 'PL/I', True],
            [201, 'PL/SQL', True],
            [202, 'PostgreSQL', True],
            [203, 'PostScript', True],
            [244, 'StandardML', True],
            [245, 'StoneScript', True],
            [246, 'SuperCollider', True],
            [240, 'SPARK', True],
            [241, 'SPARQL', True],
            [242, 'SQF', True],
            [243, 'SQL', True],
            [252, 'thinBasic', True],
            [253, 'TypoScript', True],
            [254, 'Unicon', True],
            [255, 'UnrealScript', True],
            [248, 'SystemVerilog', True],
            [249, 'T-SQL', True],
            [250, 'TCL', True],
            [251, 'Tera Term', True],
            [228, 'RPM Spec', True],
            [230, 'Ruby Gnuplot', True],
            [231, 'Rust', True],
            [224, 'REBOL', True],
            [225, 'REG', True],
            [226, 'Rexx', True],
            [227, 'Robots', True],
            [236, 'SCL', True],
            [237, 'SdlBasic', True],
            [238, 'Smalltalk', True],
            [239, 'Smarty', True],
            [232, 'SAS', True],
            [233, 'Scala', True],
            [234, 'Scheme', True],
            [235, 'Scilab', True],
            [148, 'LOL Code', True],
            [149, 'Lotus Formulas', True],
            [150, 'Lotus Script', True],
            [151, 'LScript', True],
            [144, 'Lisp', True],
            [145, 'LLVM', True],
            [146, 'Loco Basic', True],
            [147, 'Logtalk', True],
            [156, 'MapBasic', True],
            [158, 'MatLab', True],
            [159, 'mIRC', True],
            [153, 'M68000 Assembler', True],
            [154, 'MagikSF', True],
            [155, 'Make', True],
            [132, 'Java 5', True],
            [134, 'JCL', True],
            [135, 'jQuery', True],
            [128, 'IO', True],
            [129, 'ISPF Panel Definition', True],
            [130, 'J', True],
            [140, 'Latex', True],
            [141, 'LDIF', True],
            [142, 'Liberty BASIC', True],
            [143, 'Linden Scripting', True],
            [137, 'Julia', True],
            [138, 'KiXtart', True],
            [139, 'Kotlin', True],
            [180, 'Open Object Rexx', True],
            [181, 'OpenBSD PACKET FILTER', True],
            [182, 'OpenGL Shading', True],
            [183, 'Openoffice BASIC', True],
            [177, 'OCalm Brief', True],
            [178, 'OCaml', True],
            [179, 'Octave', True],
            [188, 'PARI/GP', True],
            [189, 'Pascal', True],
            [190, 'Pawn', True],
            [191, 'PCRE', True],
            [184, 'Oracle 11', True],
            [185, 'Oracle 8', True],
            [186, 'Oz', True],
            [187, 'ParaSail', True]]
