"""empty message

Revision ID: 0a00d8aa0cce
Revises: c906f8ca6628
Create Date: 2017-11-17 16:43:40.381449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a00d8aa0cce'
down_revision = 'c906f8ca6628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('date_timelive', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'user', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('pastes', 'date_timelive')
    # ### end Alembic commands ###
