"""empty message

Revision ID: ada7c64ff1a2
Revises: 0a00d8aa0cce
Create Date: 2017-11-21 17:05:03.144012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada7c64ff1a2'
down_revision = '0a00d8aa0cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['api_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###
